import React from 'react';
import { X, AlertTriangle, Shield } from 'lucide-react';

const DisclaimerModal = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-lg shadow-xl max-w-2xl w-full max-h-96 overflow-y-auto">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center space-x-3">
              <div className="bg-amber-100 p-2 rounded-lg">
                <AlertTriangle className="h-6 w-6 text-amber-600" />
              </div>
              <h2 className="text-xl font-semibold text-gray-900">
                Important Medical Disclaimer
              </h2>
            </div>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600"
            >
              <X className="h-6 w-6" />
            </button>
          </div>

          {/* Content */}
          <div className="space-y-4 text-sm text-gray-700">
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <h3 className="font-semibold text-red-900 mb-2">
                ⚠️ For Educational Purposes Only
              </h3>
              <p className="text-red-800">
                This tool is designed for educational purposes only and should NOT be used as a substitute 
                for professional medical advice, diagnosis, or treatment.
              </p>
            </div>

            <div className="space-y-3">
              <h3 className="font-semibold text-gray-900">Please understand that:</h3>
              <ul className="space-y-2 list-disc list-inside text-gray-700">
                <li>This analysis is generated by AI and may contain errors or inaccuracies</li>
                <li>Reference ranges may vary between laboratories and populations</li>
                <li>Medical test interpretation requires professional medical training</li>
                <li>Many factors can affect test results including medications, medical conditions, and timing</li>
                <li>Abnormal results don't always indicate disease, and normal results don't rule out all conditions</li>
              </ul>
            </div>

            <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
              <h3 className="font-semibold text-blue-900 mb-2">
                🩺 Always Consult Healthcare Professionals
              </h3>
              <p className="text-blue-800">
                For proper interpretation of your medical test results, please consult with qualified 
                healthcare professionals such as your doctor, physician, or medical specialist.
              </p>
            </div>

            <div className="bg-green-50 border border-green-200 rounded-lg p-4">
              <div className="flex items-start space-x-2">
                <Shield className="h-5 w-5 text-green-600 mt-0.5 flex-shrink-0" />
                <div>
                  <h3 className="font-semibold text-green-900 mb-2">Our Commitment</h3>
                  <p className="text-green-800 text-sm">
                    This tool aims to make medical information more accessible and understandable, 
                    supporting SDG 3 (Good Health and Well-being) and SDG 10 (Reduced Inequalities). 
                    However, it is not a replacement for professional medical care.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
              <h3 className="font-semibold text-gray-900 mb-2">Privacy & Security</h3>
              <p className="text-gray-700 text-sm">
                Your medical data is processed locally and is not stored on our servers. 
                However, please be cautious when sharing personal medical information online.
              </p>
            </div>
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between mt-6 pt-4 border-t border-gray-200">
            <label className="flex items-center space-x-2 text-sm text-gray-600">
              <input
                type="checkbox"
                onChange={(e) => {
                  if (e.target.checked) {
                    localStorage.setItem('medical-disclaimer-accepted', 'true');
                  }
                }}
                className="rounded border-gray-300"
              />
              <span>I understand and accept these terms</span>
            </label>
            <button
              onClick={onClose}
              className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-medium transition-colors"
            >
              Continue
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerModal;